name: rive_demo_app
description: "A demo platform for Rive."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  file_selector: ^1.1.0
  flutter:
    sdk: flutter
  image_gallery_saver_plus: ^4.0.1
  rive: ^0.14.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: true
  assets:
    # Place .riv files under assets/riv/my_demo_name/ and add the directory below:
    - assets/riv/avatar_creator/
    - assets/riv/duelist/
    - assets/riv/responsive_layouts/
    - assets/riv/feathering_button/
    - assets/riv/feathering_coin/
    - assets/riv/data_viz/
    - assets/riv/ad_widget/
    - assets/riv/rtl_language_layout/
    - assets/riv/home/
    - assets/riv/liquid_download/
    - assets/riv/scrollytelling/
    - assets/riv/scrollytelling_raster/
    - assets/riv/car_widget/
    - assets/riv/fintech/
    - assets/riv/game_character/
    - assets/riv/character_card/
    - assets/riv/car_component/
    - assets/riv/music_player/
    - assets/riv/treasure_chest/
    - assets/riv/slot_machine/
    - assets/riv/inventory/
    - assets/riv/sports_broadcast/
    - assets/riv/ai_dj/