// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbr2LDuBz9lg4NFLQsF_3oU3sfw_6Azn4',
    appId: '1:669065642915:web:309bbdc43f01e4e66d9016',
    messagingSenderId: '669065642915',
    projectId: 'rive-demo-app',
    authDomain: 'rive-demo-app.firebaseapp.com',
    storageBucket: 'rive-demo-app.firebasestorage.app',
    measurementId: 'G-00V0EE2J2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKKU5ArJ0zXrYLwbweoW_hj4ffcpgKgyM',
    appId: '1:669065642915:android:d0bab14ca429f0396d9016',
    messagingSenderId: '669065642915',
    projectId: 'rive-demo-app',
    storageBucket: 'rive-demo-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCnARq57_jf96ngNW2cw64ZHjt3xZmNE8',
    appId: '1:669065642915:ios:d958dc222db2b86b6d9016',
    messagingSenderId: '669065642915',
    projectId: 'rive-demo-app',
    storageBucket: 'rive-demo-app.firebasestorage.app',
    iosBundleId: 'app.rive.riveDemoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCnARq57_jf96ngNW2cw64ZHjt3xZmNE8',
    appId: '1:669065642915:ios:d3b23b8c2e1c96216d9016',
    messagingSenderId: '669065642915',
    projectId: 'rive-demo-app',
    storageBucket: 'rive-demo-app.firebasestorage.app',
    iosBundleId: 'com.rive.riveDemoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbr2LDuBz9lg4NFLQsF_3oU3sfw_6Azn4',
    appId: '1:669065642915:web:c730beb032cf097a6d9016',
    messagingSenderId: '669065642915',
    projectId: 'rive-demo-app',
    authDomain: 'rive-demo-app.firebaseapp.com',
    storageBucket: 'rive-demo-app.firebasestorage.app',
    measurementId: 'G-K6WCPBTQR1',
  );

}